-- Copyright Federico Valeri.
-- License: Apache License 2.0 (see the file LICENSE).

DROP TABLE IF EXISTS RG_IMAGES CASCADE;
DROP TABLE IF EXISTS RG_TEXTS CASCADE;
DROP TABLE IF EXISTS RG_TABLES CASCADE;
DROP TABLE IF EXISTS RG_REPORTS CASCADE;
DROP TABLE IF EXISTS RG_IMAGE_TYPES CASCADE;
DROP TABLE IF EXISTS RG_TEXT_TYPES CASCADE;
DROP TABLE IF EXISTS RG_TABLE_TYPES CASCADE;
DROP TABLE IF EXISTS RG_MODELS CASCADE;

DROP SEQUENCE IF EXISTS RG_REPORTS_SEQ;
DROP SEQUENCE IF EXISTS RG_IMAGES_SEQ;
DROP SEQUENCE IF EXISTS RG_TEXTS_SEQ;
DROP SEQUENCE IF EXISTS RG_TABLES_SEQ;

-- config tables
CREATE TABLE RG_MODELS (
  RMD_ID NUMBER NOT NULL PRIMARY KEY
, RMD_NAME VARCHAR2(50) NOT NULL
, RMD_START DATE NOT NULL
, RMD_END DATE
, RMD_FORMAT VARCHAR2(5) NOT NULL
);

COMMENT ON COLUMN RG_MODELS.RMD_NAME IS 'Must be equal to the JRXML file name';
CREATE INDEX RG_MODELS_IDX1 ON RG_MODELS (RMD_NAME ASC);
ALTER TABLE RG_MODELS ADD CONSTRAINT RG_MODELS_UK1 UNIQUE (RMD_NAME);

CREATE TABLE RG_IMAGE_TYPES (
  RIT_ID NUMBER NOT NULL PRIMARY KEY
, RIT_RMD_ID NUMBER NOT NULL
, RIT_NAME VARCHAR2(50) NOT NULL
, RIT_DESC VARCHAR2(255)
);

CREATE INDEX RG_IMAGE_TYPES_IDX1 ON RG_IMAGE_TYPES (RIT_NAME ASC);

ALTER TABLE RG_IMAGE_TYPES
ADD CONSTRAINT RG_IMAGE_TYPES_FK1 FOREIGN KEY (RIT_RMD_ID)
REFERENCES RG_MODELS (RMD_ID);

CREATE TABLE RG_TEXT_TYPES (
  RTT_ID NUMBER NOT NULL PRIMARY KEY
, RTT_RMD_ID NUMBER NOT NULL
, RTT_NAME VARCHAR2(50) NOT NULL
, RTT_DESC VARCHAR2(255)
);

CREATE INDEX RG_TEXT_TYPES_IDX1 ON RG_TEXT_TYPES (RTT_NAME ASC);

ALTER TABLE RG_TEXT_TYPES
ADD CONSTRAINT RG_TEXT_TYPES_FK1 FOREIGN KEY (RTT_RMD_ID)
REFERENCES RG_MODELS (RMD_ID);

CREATE TABLE RG_TABLE_TYPES (
  RTP_ID NUMBER NOT NULL PRIMARY KEY
, RTP_RMD_ID NUMBER NOT NULL
, RTP_NAME VARCHAR2(50) NOT NULL
, RTP_DESC VARCHAR2(255)
);

CREATE INDEX RG_TABLE_TYPES_IDX1 ON RG_TABLE_TYPES (RTP_NAME ASC);

ALTER TABLE RG_TABLE_TYPES
ADD CONSTRAINT RG_TABLE_TYPES_FK1 FOREIGN KEY (RTP_RMD_ID)
REFERENCES RG_MODELS (RMD_ID);

-- data tables
CREATE TABLE RG_REPORTS (
  RRE_ID NUMBER NOT NULL PRIMARY KEY
, RRE_RMD_ID NUMBER NOT NULL
, RRE_REF_ID VARCHAR2(255)
, RRE_START DATE
, RRE_END DATE
, RRE_FILENAME VARCHAR2(255)
, RRE_BINARY BLOB
, RRE_ERROR VARCHAR2(255)
);

COMMENT ON COLUMN RG_REPORTS.RRE_REF_ID IS 'Position reference id';
CREATE INDEX RG_REPORTS_IDX1 ON RG_REPORTS (RRE_RMD_ID ASC);
CREATE INDEX RG_REPORTS_IDX2 ON RG_REPORTS (RRE_REF_ID ASC);
CREATE INDEX RG_REPORTS_IDX3 ON RG_REPORTS (RRE_FILENAME ASC);
CREATE SEQUENCE RG_REPORTS_SEQ START WITH 4 NOCACHE;

ALTER TABLE RG_REPORTS
ADD CONSTRAINT RG_REPORTS_FK1 FOREIGN KEY (RRE_RMD_ID)
REFERENCES RG_MODELS (RMD_ID);

CREATE TABLE RG_IMAGES (
  RIM_ID NUMBER NOT NULL PRIMARY KEY
, RIM_RRE_ID NUMBER NOT NULL
, RIM_RIT_ID NUMBER NOT NULL
, RIM_VALUE BLOB
);

CREATE INDEX RG_IMAGES_IDX1 ON RG_IMAGES (RIM_RRE_ID ASC);
CREATE INDEX RG_IMAGES_IDX2 ON RG_IMAGES (RIM_RIT_ID ASC);
CREATE SEQUENCE RG_IMAGES_SEQ START WITH 1 NOCACHE;

ALTER TABLE RG_IMAGES
ADD CONSTRAINT RG_IMAGES_FK1 FOREIGN KEY(RIM_RRE_ID)
REFERENCES RG_REPORTS (RRE_ID);

ALTER TABLE RG_IMAGES
ADD CONSTRAINT RG_IMAGES_FK2 FOREIGN KEY (RIM_RIT_ID)
REFERENCES RG_IMAGE_TYPES (RIT_ID);

CREATE TABLE RG_TEXTS (
  RTE_ID NUMBER NOT NULL PRIMARY KEY
, RTE_RRE_ID NUMBER NOT NULL
, RTE_RTT_ID NUMBER NOT NULL
, RTE_VALUE VARCHAR2(4000)
);

CREATE INDEX RG_TEXTS_IDX1 ON RG_TEXTS (RTE_RRE_ID ASC);
CREATE INDEX RG_TEXTS_IDX2 ON RG_TEXTS (RTE_RTT_ID ASC);
CREATE SEQUENCE RG_TEXTS_SEQ START WITH 14 NOCACHE;

ALTER TABLE RG_TEXTS
ADD CONSTRAINT RG_TEXTS_FK1 FOREIGN KEY(RTE_RRE_ID)
REFERENCES RG_REPORTS (RRE_ID);

ALTER TABLE RG_TEXTS
ADD CONSTRAINT RG_TEXTS_FK2 FOREIGN KEY (RTE_RTT_ID)
REFERENCES RG_TEXT_TYPES (RTT_ID);

CREATE TABLE RG_TABLES (
  RTB_ID NUMBER NOT NULL PRIMARY KEY
, RTB_RRE_ID NUMBER NOT NULL
, RTB_RTP_ID NUMBER NOT NULL
, RTB_CELL0 VARCHAR2(4000)
, RTB_CELL1 VARCHAR2(4000)
, RTB_CELL2 VARCHAR2(4000)
, RTB_CELL3 VARCHAR2(4000)
, RTB_CELL4 VARCHAR2(4000)
, RTB_CELL5 VARCHAR2(4000)
, RTB_CELL6 VARCHAR2(4000)
, RTB_CELL7 VARCHAR2(4000)
, RTB_CELL8 VARCHAR2(4000)
, RTB_CELL9 VARCHAR2(4000)
, RTB_CELL10 VARCHAR2(4000)
, RTB_CELL11 VARCHAR2(4000)
, RTB_CELL12 VARCHAR2(4000)
, RTB_CELL13 VARCHAR2(4000)
, RTB_CELL14 VARCHAR2(4000)
, RTB_CELL15 VARCHAR2(4000)
, RTB_CELL16 VARCHAR2(4000)
, RTB_CELL17 VARCHAR2(4000)
, RTB_CELL18 VARCHAR2(4000)
, RTB_CELL19 VARCHAR2(4000)
, RTB_CELL20 VARCHAR2(4000)
, RTB_CELL21 VARCHAR2(4000)
, RTB_CELL22 VARCHAR2(4000)
, RTB_CELL23 VARCHAR2(4000)
, RTB_CELL24 VARCHAR2(4000)
, RTB_CELL25 VARCHAR2(4000)
, RTB_CELL26 VARCHAR2(4000)
, RTB_CELL27 VARCHAR2(4000)
, RTB_CELL28 VARCHAR2(4000)
, RTB_CELL29 VARCHAR2(4000)
);

CREATE INDEX RG_TABLES_IDX1 ON RG_TABLES (RTB_RRE_ID ASC);
CREATE INDEX RG_TABLES_IDX2 ON RG_TABLES (RTB_RTP_ID ASC);
CREATE SEQUENCE RG_TABLES_SEQ START WITH 4 NOCACHE;

ALTER TABLE RG_TABLES
ADD CONSTRAINT RG_TABLES_FK1 FOREIGN KEY (RTB_RRE_ID)
REFERENCES RG_REPORTS (RRE_ID);

ALTER TABLE RG_TABLES
ADD CONSTRAINT RG_TABLES_FK2 FOREIGN KEY (RTB_RTP_ID)
REFERENCES RG_TABLE_TYPES (RTP_ID);
