name: main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  run-tests:
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      fail-fast: true
      matrix:
        java: [ '8' ]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          architecture: 'x64'
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: Run unit tests
        run: |
          mvn -V -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false \
          -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 --no-transfer-progress \
          clean test
      - name: Run integration tests
        run: |
          mvn -V -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false \
          -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 --no-transfer-progress \
          clean test -Pint
